### ISSUE TITLE
Why not using sendAction

### ISSUE THREAD

**Issue by ghost** [abuiles/borrowers-2016#12]
Why not using `this.sendAction('actionName')` in the component (example 1), instead of passing action using `(action actionName)` (example 2)? Is this just matter of style? Or do you have any other purpose to do so?

**Example 1**

```
  {{articles/edit-form
    model=model
    save="actionName"
  }}
```

**Example 2**

```
  {{articles/edit-form
    model=model
    save=(action save)
    cancel=(action cancel)
  }}
```

Thank you for your time viewing this question. :rocket:

**Comment by abuiles** [comment]
I wanted to show that both APIs were possible.

I need to update the book, but prefer `(action cancel)` over `sendAction`.

--
Adolfo Builes

**Comment by ghost** [comment]
For future readers

```
same=(action 'save')
```

This is called closure action and there are serveral advantages compare to tranditional `sendAction`.

1. It return values since it is a function, `sendAction` does NOT return value
2. It fails immediately if the action is not found, `sendAction` only raise error lazily by design
3. It is a value with no special tratement just like other value you pass into a component
